services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: orders
    ports: ["5432:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U app -d orders"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  redpanda:
    image: redpandadata/redpanda:v25.2.2
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports: ["9092:9092"]
    volumes: [redpanda_data:/var/lib/redpanda/data]

  order-service:
    build: .
    environment:
      DATABASE_URL: postgresql://app:app@postgres:5432/orders
      REDIS_URL: redis://redis:6379/0
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SERVICE_NAME: order-service
    ports: ["8000:8000"]
    depends_on:
      postgres: {condition: service_healthy}
      redpanda: {condition: service_started}
      redis: {condition: service_started}
    command: ["uvicorn","services.order_service.app:app","--host","0.0.0.0","--port","8000"]

  inventory-service:
    build: .
    environment:
      DATABASE_URL: postgresql://app:app@postgres:5432/orders
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SERVICE_NAME: inventory-service
    depends_on: {redpanda: {condition: service_started}}
    command: ["python","-m","services.inventory_service.worker"]

  payment-service:
    build: .
    environment:
      DATABASE_URL: postgresql://app:app@postgres:5432/orders
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SERVICE_NAME: payment-service
    depends_on: {redpanda: {condition: service_started}}
    command: ["python","-m","services.payment_service.worker"]

  notification-service:
    build: .
    environment:
      DATABASE_URL: postgresql://app:app@postgres:5432/orders
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SERVICE_NAME: notification-service
    depends_on: {redpanda: {condition: service_started}}
    command: ["python","-m","services.notification_service.worker"]

  analytics-service:
    build: .
    environment:
      DATABASE_URL: postgresql://app:app@postgres:5432/orders
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SERVICE_NAME: analytics-service
    depends_on: {redpanda: {condition: service_started}}
    command: ["python","-m","services.analytics_service.worker"]

volumes:
  postgres_data:
  redpanda_data:
